baseURL = "https://desperadoshi.github.io/nfsdoc/"
theme = "dot"
publishDir = "docs"

[params]
primaryColor = "#02007e"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  languageCode = "en-us"
  title = "NFS"
  dateFormat = "2 January 2019"
  home = "Home"
  logo = "NFS"
  copyright = "NFS are copyright © NPU CFD Group 2019."

    # navigation
    [Languages.en.menu]
    
      [[Languages.en.menu.main]]
        weight = 2
        name = "Demo"
        url = "/demo_cases"
        
      [[Languages.en.menu.main]]
        weight = 2
        name = "Inputs"
        url = "/inputs"
        
      [[Languages.en.menu.main]]
        weight = 2
        name = "Install"
        url = "/install"
        
#      [[Languages.en.menu.main]]
#        weight = 2
#        name = "pages"
#        url = "/pages"
#        hasChildren = true
#
#          [[Languages.en.menu.main]]
#          parent = "pages"
#          name = "contact"
#          URL = "/contact"
#          weight = 1

    # banner
    [Languages.en.params.banner]
      title = "NPU Flux-reconstruction Simulation - NFS"
      description = "Next Generation of CFD Software. Need For Speed in CFD"
      image = "banner.jpeg"
      placeholder = "Have a question? Just ask here or enter terms"

    # Topics
    [Languages.en.params.topics]
      title = "Find your answer by subject"

#     # call to action
#     [Languages.en.params.cta]
#       enable = false
#       title = "Didn't find an answer to your question?"
#       description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
#       btnText = "contact us"
#       btnURL = "/contact"
# 
#     # contact
#     [Languages.en.params.contact]
#       title = "Got Any Questions"
#       content = "Submit the form and confirm your email address at <a class='text-primary' href='https://formspree.io/'>Formspree</a> Then add the following lines to contact page YAML Front Matter."

    # footer social icon
    [[Languages.en.socialIcon]]
      icon = "ti-facebook"
      URL = "/#"

